### PR TITLE
Add more Scanner CloudFormation stack Outputs

### PR DESCRIPTION
**Pull request by tdbj4h**
The AWS CloudFormation Scanner stack does not output the following ARNs for resources it creates which would be really useful to have as outputs:

ScannerQueueDLQ
ScannerDeadLetterLambda
ScannerQueue
ScannerLogGroup
ScannerDeadLetterLogGroup

This change will output the above resources ARNs.

Have tested the changes in my own AWS account:

scanner-output

### CODE REVIEW

**Comment by felipecosta09** [comment]
The code itself LGTM, but I don't know if there are any implications on adding these additional outputs... any comments @jack-c-tang ?

**Comment by jack-c-tang** [comment]
Hi @tdbj4h, thank you for the enhancement request. The templates in the repository are for reviewing, so changes done here won't have effect on actual deployment. I'll bring back this PR to team for discussing it.

For the output data you list I have some questions:
* Why would you need `ScannerDeadLetterLambda` and `ScannerQueue` ARN? They are supposed to be used internally, so I'm a bit not in favor of output them.
* For log group ARN, AFAIK most use cases require log group name instead of log group ARN. Is there any case that need to use the ARN?

**Comment by felipecosta09** [comment]
> Hi @tdbj4h, thank you for the enhancement request. The templates in the repository are for reviewing, so changes done here won't have effect on actual deployment. I'll bring back this PR to team for discussing it.
> 
> For the output data you list I have some questions:
> 
> * Why would you need `ScannerDeadLetterLambda` and `ScannerQueue` ARN through the outputs? They are supposed to be used internally, so I'm a bit not in favor of output them.
> * For log group ARN, AFAIK most use cases require log group name instead of log group ARN. Is there any case that need to use the ARN?

For the `ScannerQueue` I see a use case since we can use it to trigger new files to scan, just like the [Full Scan Plugin](https://github.com/trendmicro/cloudone-filestorage-plugins/tree/master/scan-triggers/aws-python-bucket-full-and-scheduled-scan) does, actually one thing that I'm working on is to have a single template that combines a FSS template deployment and the [Full Scan Plugin](https://github.com/trendmicro/cloudone-filestorage-plugins/tree/master/scan-triggers/aws-python-bucket-full-and-scheduled-scan) all together so the `ScannerQueue` ARN will actually help. I leave it for @tdbj4h or anybody that want to jump in for the other ones...

**Comment by tdbj4h** [comment]
Hi all, thanks for taking time to review this!

To answer the first point around why we want the Scanner Queue and the Scanner Dead Letter - we would like to do queue depth monitoring on the scanner queue. In the page https://cloudone.trendmicro.com/docs/file-storage-security/faq/ it states to use the queue depth to monitor perform - 
image

The reason for the Scanner Dead Letter function ARN was purely just to capture as much output as possible from the proposed change. I'd be happy to remove that.

To answer the question around the use of ARNs rather than a resource name, I thought it would be beneficial to follow how the existing template works which almost exclusively outputs ARNs rather than names. As suggested, we actually want the Log Group name, not the ARN but wanted to work with how it's already been done - I'd be happy to update the PR with the Log Group name output rather than the ARN as our end goal is to get the name of the Log Group.

Let me know if you'd like me to do any of the above changes!

**Comment by jack-c-tang** [comment]
@tdbj4h thank you for the suggestion. I'll create a case on our end to publish the templates to S3 and this repository at once. That would include ScannerQueue ARN and log group names (because most of the CW operations need it instead of ARN). We'll also review if we can add more outputs to the storage stack.

**Comment by felipecosta09** [comment]
Hey @jack-c-tang, any updates?

**Comment by andrew-c-lee** [comment]
Hi @felipecosta09 @tdbj4h,
The updated version added more information to the CF output has since publish. You could find the change in https://github.com/trendmicro/cloudone-filestorage-deployment-templates/pull/98.

**Comment by felipecosta09** [comment]
> 

Thanks @andrew-c-lee should we close this PR then?

Any other comments @tdbj4h ?

**Comment by jack-c-tang** [comment]
Fixed in #98

**Pull request closed without merging**
